sudo: required
language: node_js
node_js:
  - "11"
  - "10"
  - "8"
services:
  - xvfb
env:
  global:
    - BACKEND_CPU=true
  matrix:
    - ENV=browser
    - ENV=node
addons:
  chrome: stable
script:
  - if [ $ENV == 'browser' ]; then npm run test-browser; fi
  - if [ $ENV == 'node' ]; then npm run test-node; fi
  - npm run build